### ISSUE TITLE
Upgrade issue for 2017.3 EAP

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#243]
I just upgraded IntelliJ IDEA to the 2017.3 EAP and am told that DLanguage 1.10 is an upgrade to 1.14-SNAPSHOT.

**Comment by pirocks** [comment]
Perhaps #240 would fix this?

**Comment by russel** [comment]
I am not sure, I had thought there was a newer version already in place on the JetBrains servers so was surprised to see 1.10 mentioned at all. I am assuming the plugin can be installed into 2017.3 EAP, maybe I should do that and not rely on the 2017.2 to 2017.3 upgrading.

**Comment by russel** [comment]
It is worth adding that a newly built 1.14-SNAPSHOT plugin will not install into 2017.3 because of the version check, i.e. 173.XXX is the new version number for IntelliJ IDEA and this plugin isn't happy with that number.

**Comment by russel** [comment]
I set 2017.2 as the base IDEA version, 1.1.4 as the Kotlin version, and also tried to set 173.* as acceptable version. I got a plugin build and it loaded into 2017.3 but then failed with class not found failure. So I am clearly missing something about how to try and get something installing in 2017.3.

**Comment by SingingBush** [comment]
in the plugin we define a minimum intellij version as well as a max supported version. The current versions of the plugin will support any 2017.1.* and 2017.2.* versions of idea but it will not work with 2017.3 yet (see the [failing EAP builds](https://travis-ci.org/intellij-dlanguage/intellij-dlanguage/jobs/273223450)). So the new release would not solve the 2017.3 problem.

The reason the plugin repo thinks v1.10 is suitable is because that version was released with a minimum intellij version but no max version. This was bad, the best thing thing to do about that would be to remove it from the repository alltogether (and possibly older versions). Currently @kingsleyh would need to do that.

Let's get this release out then focus on 2017.3 support

**Comment by SingingBush** [comment]
It's certainly broken on 2017.3, I've created a new branch https://github.com/intellij-dlanguage/intellij-dlanguage/tree/feature/2017.3-support to use for this. I've not got time to look at it now but if you are able to take a look check that branch out and see what's needed to get it running again. The stack trace was:

```
Plugin 'net.masterthought.dlanguage' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: net/masterthought/dlanguage/DLanguage
    at net.masterthought.dlanguage.DLanguageFileTypeFactory.createFileTypes(DLanguageFileTypeFactory.java:11)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:308)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:268)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:459)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:171)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:158)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:466)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:418)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:404)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: net.masterthought.dlanguage.DLanguage PluginClassLoader[net.masterthought.dlanguage, 1.14-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@46b26c4f
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 more
```

**Comment by SingingBush** [comment]
@russel can you do a new build from the develop branch and test that. I just ran it locally and it seemed fine but I haven't tested it thoroughly.

**Comment by pirocks** [comment]
It's seems to be passing now: https://travis-ci.org/intellij-dlanguage/intellij-dlanguage/jobs/273640844

**Comment by russel** [comment]
I built from scratch and loaded and it all seems to work. Is it worth updating the build Idea to 2017.2 rather than 2017.1?

**Comment by SingingBush** [comment]
I don't think there's any gain in increasing minimum version. We should keep targeting all 2017 versions for now. I'll try getting around to tagging a new release tomorrow.

**Comment by SingingBush** [comment]
v1.13.1 is now pending approval and will support 2017.3

https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea
