### PR TITLE
 #920 upgrade grammarkit plugin to fix build with version 2024.1

### LINKED ISSUE #920: Support for Intellij 2024.1
The 1.33 release should support Intellij 2024.1. If the minimum-supported version needs to increase that's fine but ideally 2023 should still be supported if possible. 

So far only EAP releases are available for testing so it's not yet known if the failing build will continue to be a problem. 

GitHub Action failed with:

```
Error: Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/collections/immutable/PersistentList
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.<clinit>(ExtensionPointImpl.kt:71)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.kt:212)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.kt:186)
	at com.intellij.core.CoreApplicationEnvironment.registerExtensionPoint(CoreApplicationEnvironment.java:224)
	at com.intellij.core.CoreApplicationEnvironment.registerExtensionPoint(CoreApplicationEnvironment.java:214)
	at com.intellij.core.CoreApplicationEnvironment.registerApplicationExtensionPoint(CoreApplicationEnvironment.java:229)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:93)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:72)
	at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:152)
	at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:55)
	at org.intellij.grammar.Main.main(Main.java:38)
Caused by: java.lang.ClassNotFoundException: kotlinx.collections.immutable.PersistentList
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

### LINKED ISSUE #930: Replace MockJdkUsage by a custom implementation
Since version 2024.1, MockSdk is deprecated and will be removed In version 2024.2.
We need to replace it with a custom implementation (see https://github.com/JetBrains/intellij-community/blob/master/java/testFramework/src/com/intellij/testFramework/IdeaTestUtil.java#L100 as example)

### PR DESCRIPTION
**Pull request by etienne02**
Closes #920 
Closes #930

### CODE REVIEW

File: src/test/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServerTest.java
Comment (SingingBush) [inline src/test/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServerTest.java:1]: why not just change the _getProjectJDK_ function in LightDlangTestCase?

Comment (etienne02) [reply src/test/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServerTest.java:1]: It’s because the SDK is only used there, so no need to setup a sdk (create a temporary folder on disk ...) for just one test.
