### ISSUE TITLE
Lambda breaks debugger

### ISSUE THREAD

**Issue by bamarc** [intellij-dlanguage/intellij-dlanguage#302]
The following code stops the debugger the moment it hits it.

```
import std.file;
import std.algorithm;
auto fileList = dirEntries(inputpath, SpanMode.shallow).filter!(a => a.isFile);
```

```
[Inferior 1 (process 7296) exited with code 01]
23:24:46.453 < [notify] thread-exited: [id: "1", group-id: "i1"]
23:24:46.453 < [notify] thread-group-exited: [id: "i1", exit-code: "01"]
23:24:46.453 < [exec] stopped: [reason: "exited", exit-code: "01"]
23:24:46.453 8> -thread-info
23:24:46.495 <8 [immediate] done
23:24:46.533 9> -stack-list-frames
23:24:46.628 <9 [immediate] error: [msg: "No registers."]
```

**Comment by pirocks** [comment]
I'm having trouble compiling this example, on dmd 2.77:
```
 /usr/include/dmd/druntime/import/core/memory.d(827): Error: fakePureErrno cannot be interpreted at compile time, because it has no available source code
/usr/include/dmd/phobos/std/typecons.d(5434):        called from here: pureMalloc(200LU)
/usr/include/dmd/phobos/std/typecons.d(5530):        called from here: this._refCounted.initialize(_param_0, _param_1, _param_2)
/usr/include/dmd/phobos/std/file.d(3920):        called from here: this.impl.this(pathname, mode, followSymlink)
/usr/include/dmd/phobos/std/file.d(4000):        called from here: ((DirIterator __slDirIt145 = DirIterator(RefCounted(RefCountedStore(null)));) , __slDirIt145).this(path, mode, followSymlink)
source/app.d(8):        called from here: dirEntries("/home/francis/IdeaProjects/untitled5", cast(SpanMode)0, true)
source/app.d(8):        called from here: filter(dirEntries("/home/francis/IdeaProjects/untitled5", cast(SpanMode)0, true))
```

**Comment by bamarc** [comment]
Here is a test project which compiles with dmd 2.77:

[lambdaError.zip](https://github.com/intellij-dlanguage/intellij-dlanguage/files/1504235/lambdaError.zip)

**Comment by pirocks** [comment]
Thanks for the .zip

**Comment by pirocks** [comment]
I have reproduced this issue.
